-- Follow-up to the public source review: identify the captured report pages and
-- explain precisely what the submitted reconstruction screenshots can test.
SET @investigation_slug = 'nolan-wells-garrett-discovery-phone-timeline';
SET @visual_update_marker = '## What the public reconstruction adds';
SET @visual_update = '

## What the public reconstruction adds

The [Justice for Nolan Wells account-order timeline](https://justicefornolanwells.com/) supplied for this update raises several distinct questions. It reports that storing phones aboard boats while people swam was a common practice, which makes a phone returning without its owner possible. That practice does not establish Nolan’s later intent or whereabouts. The site identifies Jax as the clearest publicly named direct narrator of an alleged invitation and refusal to board; Katie’s reported understanding was that Nolan was leaving with friends. Warren’s later account of Nolan deciding to stay requires its own source-of-knowledge check because the site places Warren’s last personal visual contact earlier. The claimed alternative ride still lacks a publicly identified vessel, operator or arrangement. These are attributed witness accounts and editorial comparisons, not new findings made by The King’s Take.

The submitted Reconstruction Lab screenshots show why evidence labels matter. The Triton view uses reported Garmin event times, but the line between points and animation speed are modeled. The yacht route, departure time and speed are editable scenario assumptions. Its 3D perspectives may help test sightlines and travel feasibility; they cannot establish an actual passenger list, a precise intermediate position or what anyone saw. [Open the Reconstruction Lab](https://justicefornolanwells.com/reconstruction-lab) and inspect each object’s Evidence and Checks tabs before drawing a conclusion.

### Browse the displayed Garrett pages

The site now hosts a [searchable 292-page visual copy](https://justicefornolanwells.com/garrett-report) and a [downloadable PDF](https://justicefornolanwells.com/media/phone-forensics-2026-09-24/garrett-discovery-stream-framebook.pdf). Its editors assembled still frames from four public livestreams to cover the numbered pages of the 261-page Snapchat Conversation Report, with extra views where pages scrolled beyond one screen and a GPS appendix. Printed page 151 is only partly visible. Search text was generated by OCR, so quotations and names should be checked against page images. This is a substantial public viewing source, but it is not the original Garrett digital report, native extraction or authenticated source records. [Read its provenance and limitations](https://justicefornolanwells.com/phone-forensics).

An app event, account indicator or phone location does not by itself identify the person using or carrying a device. A vessel GPS trace establishes movement of the tracked vessel, not every passenger. The released Sea Tow call supports a real boat emergency; it does not authenticate the alleged beach conversation. The record remains open on those separate questions.

Image note: the feature image is a branded editorial treatment of a reader-supplied photograph. It is illustrative and is not case evidence.';

UPDATE `posts`
SET `content` = CASE
      WHEN LOCATE(@visual_update_marker, `content`) = 0 THEN CONCAT(`content`, @visual_update)
      ELSE `content`
    END,
    `updatedAt` = CURRENT_TIMESTAMP
WHERE BINARY `slug` = BINARY @investigation_slug;
