CREATE TABLE IF NOT EXISTS agent_controls (
 id INT PRIMARY KEY, feed_enabled BOOLEAN NOT NULL DEFAULT TRUE,
 map_enabled BOOLEAN NOT NULL DEFAULT TRUE, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
INSERT IGNORE INTO agent_controls (id,feed_enabled,map_enabled) VALUES (1,TRUE,TRUE);
CREATE TABLE IF NOT EXISTS agent_worker_runs (
 kind VARCHAR(16) NOT NULL, slot_key VARCHAR(32) NOT NULL, status VARCHAR(20) NOT NULL,
 notes TEXT NULL, started_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, completed_at TIMESTAMP NULL,
 PRIMARY KEY(kind,slot_key)
);
ALTER TABLE research_agent_records ADD COLUMN auto_published BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE research_agent_records ADD COLUMN geo_source VARCHAR(1024) NULL;
