export const REALM_COPY = {
  heroTitle: 'The Ancestor Realm',
  heroSubtitle: 'Walk among those who came before. Their wisdom lives in the roots of this sacred ground.',
  enterButton: 'Enter the Garden',
  loadingMessage: 'The ancestors are preparing your path...',
  onboardingTitle: 'Plant Your Family Tree',
  onboardingSubtitle: 'Begin with yourself and trace back to the elders whose names were erased from history.',
  step1Title: 'Tell Us About Yourself',
  step1Subtitle: 'You are the trunk. Your roots run deeper than you know.',
  step2Title: 'Your Parents',
  step2Subtitle: 'Two branches. Two bloodlines. Two paths to the past.',
  step3Title: 'Your Grandparents',
  step3Subtitle: 'The four corners of your foundation. Their stories are your inheritance.',
  step4Title: 'Your Sacred Tree',
  step4Subtitle: 'Seven souls. Seven flames. This is where your journey begins.',
  saveButton: 'Plant in the Garden',
  savedSuccess: 'Your ancestors have been welcomed into the realm.',
  gardenWelcome: (name: string) => `Welcome, ${name}. The garden grows with your lineage.`,
  chatPlaceholder: 'Speak to your ancestors...',
  chatWelcome: 'I am the keeper of this sacred ground. Ask, and the elders shall answer.',
} as const
