import { useState, type FormEvent } from 'react';
import { Link } from 'react-router';
import { ArrowUpRight, Check, Crown, Globe, CalendarDays, LayoutDashboard, PenTool, ArrowRight, CheckCircle2 } from 'lucide-react';
import { trpc } from '@/providers/trpc';
import { studioPackages, type StudioInquiry } from '../../contracts/brand-studio';
const inputClass = 'mt-2 w-full rounded-lg border border-white/15 bg-[#101b28] px-4 py-3 text-base text-[#F0EBE1] outline-none focus:border-[#FFB840]';
const linkClass = 'inline-flex items-center justify-center gap-2 rounded-full bg-[#FFB840] px-6 py-3 font-semibold text-[#101b28] transition hover:bg-[#ffd485]';
export default function BrandStudioPage() {
  const [form, setForm] = useState({ name: '', email: '', phone: '', business: '', package: 'Business Identity' as StudioInquiry['package'], budget: 'Need guidance' as StudioInquiry['budget'], timeline: 'Exploring options' as StudioInquiry['timeline'], website: '', message: '', consent: false, companyWebsite: '' });
  const [sent, setSent] = useState(false);
  const inquiry = trpc.brandStudio.inquire.useMutation({ onSuccess: () => setSent(true) });
  const choose = (name: StudioInquiry['package']) => { setForm(current => ({ ...current, package: name })); document.getElementById('studio-inquiry')?.scrollIntoView({ behavior: 'smooth' }); };
  const submit = (event: FormEvent) => { event.preventDefault(); if (!form.consent) return; inquiry.mutate({ ...form, consent: true }); };
  return <main className="min-h-screen overflow-x-hidden bg-[#101b28] text-[#F0EBE1]">
    <section className="relative px-6 pb-16 pt-32 md:px-12 lg:pb-24">
      <div className="pointer-events-none absolute inset-0 bg-[radial-gradient(ellipse_at_top_right,rgba(255,184,64,0.12),transparent_65%)]" />
      <div className="relative mx-auto grid max-w-6xl items-center gap-12 lg:grid-cols-[1.1fr_1fr]">
        <div><p className="mb-6 flex items-center gap-2 text-xs uppercase tracking-[0.2em] text-[#FFB840]"><Crown size={18} /> AASOTU Media Group LLC · Brand Studio</p>
          <h1 className="text-5xl leading-[1.04] tracking-tight sm:text-6xl lg:text-7xl">A presence<br />worthy of<br /><span className="text-[#FFB840]">your vision.</span></h1>
          <p className="mt-6 max-w-lg text-lg leading-relaxed text-[#C9B99A]">Your brand, website, and words—built together. I help authors, creators, and businesses turn their ideas into a professional online home people can find, recognize, and use.</p>
          <p className="mt-4 text-sm text-[#C9B99A]">Work directly with Ronald Lee King, founder of AASOTU Media Group LLC.</p>
          <div className="mt-8 flex flex-wrap gap-3"><a href="#studio-inquiry" className={linkClass}>Tell me about your project <ArrowUpRight size={18}/></a><a href="#studio-work" className="rounded-full border border-white/20 px-6 py-3 hover:border-[#FFB840]">See the work</a></div>
        </div>
        <div className="rounded-2xl border border-[#FFB840]/25 bg-[#182635] p-6 shadow-2xl sm:p-8">
          <div className="mb-8 flex items-center justify-between border-b border-white/10 pb-5"><span className="text-sm uppercase tracking-widest text-[#FFB840]">Brand Studio</span><span className="text-xs text-[#C9B99A]">Your launch, connected</span></div>
          <p className="text-3xl leading-tight">One creative partner.<br />A complete presence.</p>
          <div className="mt-8 grid grid-cols-2 gap-3">{[{icon: Crown, title: 'Identity', text: 'A recognizable look'},{icon: Globe, title: 'Website', text: 'A home for your work'},{icon: CalendarDays, title: 'Connections', text: 'Booking & inquiries'},{icon: PenTool, title: 'Words', text: 'A clear message'}].map(({icon: Icon,title,text}) => <div key={title} className="rounded-xl border border-white/10 bg-[#101b28]/60 p-4"><Icon className="mb-4 text-[#FFB840]" size={22}/><h2 className="text-lg">{title}</h2><p className="mt-1 text-xs text-[#C9B99A]">{text}</p></div>)}</div>
          <p className="mt-6 border-t border-white/10 pt-4 text-xs leading-relaxed text-[#C9B99A]">Built around your customers and your goals. Clear scope. Direct communication. A practical handoff.</p>
        </div>
      </div>
    </section>
    <section id="studio-work" className="scroll-mt-24 border-y border-white/10 bg-[#F0EBE1] px-6 py-16 text-[#182635] md:px-12">
      <div className="mx-auto grid max-w-6xl gap-10 lg:grid-cols-2"><div><p className="text-xs uppercase tracking-[0.18em] text-[#866021]">Selected work · Volunteer project</p><h2 className="mt-4 text-4xl">Golden Clippers</h2><p className="mt-5 text-lg leading-relaxed">A digital home for a barbershop, with customer scheduling and an owner admin panel. A project I built to put my skills to work for a real business.</p><p className="mt-4 text-sm leading-relaxed text-[#182635]/75">The goal: bring the business online and give the owner a practical way to manage appointments. This portfolio example shows the kind of customer and owner experience we can discuss for your project.</p><a href="https://goldenclippers2.com" target="_blank" rel="noopener noreferrer" className="mt-6 inline-flex items-center gap-2 border-b border-[#182635] pb-1 font-semibold">Visit Golden Clippers <ArrowUpRight size={17}/></a></div>
        <div className="space-y-3">{[{icon: Globe,title: 'Public business website',text: 'A place for customers to find the business and its services.'},{icon: CalendarDays,title: 'Client scheduling',text: 'A booking flow designed around the business.'},{icon: LayoutDashboard,title: 'Owner admin panel',text: 'A dedicated workspace for managing appointments.'}].map(({icon: Icon,title,text}) => <div key={title} className="flex gap-4 rounded-xl border border-[#182635]/15 bg-white/60 p-5"><Icon className="mt-1 shrink-0 text-[#866021]" size={24}/><div><h3 className="text-xl">{title}</h3><p className="mt-1 text-sm text-[#182635]/75">{text}</p></div></div>)}</div>
      </div>
    </section>
    <section id="studio-packages" className="mx-auto max-w-6xl scroll-mt-24 px-6 py-16 md:py-24">
      <p className="text-xs uppercase tracking-[0.18em] text-[#FFB840]">Choose your starting point</p><h2 className="mt-4 text-4xl sm:text-5xl">Built to fit your next move.</h2><p className="mt-4 max-w-2xl text-[#C9B99A]">Starting prices for a defined scope. We agree on the deliverables, schedule, and final quote before work begins.</p>
      <div className="mt-10 grid gap-5 lg:grid-cols-3">{studioPackages.map((item,i) => <article key={item.name} className={`flex flex-col rounded-2xl border p-6 ${i === 2 ? 'border-[#FFB840]/60 bg-[#25364B]' : 'border-white/15 bg-[#182635]'}`}><p className="text-xs uppercase tracking-widest text-[#FFB840]">{i === 0 ? 'Identity' : i === 1 ? 'Authors & creators' : 'Businesses'}</p><h3 className="mt-4 text-3xl">{item.name}</h3><p className="mt-2 text-sm text-[#C9B99A]">{item.audience}</p><p className="mb-6 mt-6 text-4xl">{item.price}<span className="ml-2 text-xs text-[#C9B99A]">starting price</span></p><ul className="space-y-3">{item.features.map(feature => <li key={feature} className="flex gap-2 text-sm leading-relaxed"><Check size={16} className="mt-1 shrink-0 text-[#FFB840]"/>{feature}</li>)}</ul><p className="mb-6 mt-6 text-xs leading-relaxed text-[#C9B99A]">{item.note}</p><button onClick={() => choose(item.name)} className={`${linkClass} mt-auto w-full`}>Discuss this package <ArrowRight size={16}/></button></article>)}</div>
      <div className="mt-5 grid gap-5 sm:grid-cols-2"><div className="rounded-xl border border-white/15 p-6"><h3 className="text-2xl">Writing & Copy <span className="text-lg text-[#FFB840]">from $300</span></h3><p className="mt-3 text-sm leading-relaxed text-[#C9B99A]">One defined writing project up to 1,500 words, such as website copy, an author introduction, or a promotional piece. Includes two revision rounds. Books and larger projects are quoted separately.</p><button onClick={() => choose('Writing & Copy')} className="mt-4 text-[#FFB840] underline underline-offset-4">Request writing support</button><Link to="/writing-services" className="ml-4 text-sm underline">More writing services</Link></div><div className="rounded-xl border border-white/15 p-6"><h3 className="text-2xl">Monthly Care <span className="text-lg text-[#FFB840]">$79/month</span></h3><p className="mt-3 text-sm leading-relaxed text-[#C9B99A]">Routine site checks and up to 30 minutes of small content updates per month for an agreed website. New features, emergency repair work, hosting, and provider fees are separate.</p><button onClick={() => choose('Monthly Care')} className="mt-4 text-[#FFB840] underline underline-offset-4">Ask about ongoing care</button></div></div>
      <p className="mt-6 text-sm leading-relaxed text-[#C9B99A]">Domain registration, hosting, paid software, transaction fees, and applicable taxes are additional. Accounts are set up in your name where supported. For website packages, the proposed payment schedule is 50% to begin, 30% at design approval, and 20% before launch, subject to your written project agreement.</p>
    </section>
    <section className="border-y border-white/10 bg-[#182635] px-6 py-16 md:px-12"><div className="mx-auto max-w-6xl"><h2 className="text-3xl sm:text-4xl">Why a website is more than a page.</h2><p className="mt-4 max-w-3xl leading-relaxed text-[#C9B99A]">A professional launch brings together planning, visual identity, writing, responsive design, development, integrations, testing, and handoff. Agencies often divide this work among several roles. I bring these disciplines together as your direct creative partner. The price reflects the scope and the work required to make it useful.</p><div className="mt-8 grid gap-5 md:grid-cols-3">{[['01','Discover','Tell me who you serve and what you want visitors to do.'],['02','Build & review','Agree on the scope, review the design, and refine the details.'],['03','Launch & handoff','Check the agreed features, launch, and learn how to manage your site.']].map(([n,title,body]) => <div key={n}><p className="text-sm text-[#FFB840]">{n}</p><h3 className="mt-2 text-2xl">{title}</h3><p className="mt-2 text-sm leading-relaxed text-[#C9B99A]">{body}</p></div>)}</div></div></section>
    <section id="studio-inquiry" className="mx-auto grid max-w-6xl scroll-mt-24 gap-10 px-6 py-16 md:py-24 lg:grid-cols-[0.8fr_1.2fr]">
      <div><p className="text-xs uppercase tracking-[0.18em] text-[#FFB840]">Let's build your presence</p><h2 className="mt-4 text-4xl">Start with<br />a conversation.</h2><p className="mt-5 leading-relaxed text-[#C9B99A]">Tell me about your business, book, or idea. I'll review your goals and contact you about the scope and next steps. Sending an inquiry does not commit you to a purchase.</p><a href="mailto:aasotumediagroup@gmail.com" className="mt-5 block break-all text-[#FFB840] underline">aasotumediagroup@gmail.com</a><p className="mt-5 text-sm text-[#C9B99A]">Ronald Lee King<br />AASOTU Media Group LLC · #TheKingsTake</p></div>
      {sent ? <div role="status" className="rounded-2xl border border-emerald-300/30 bg-emerald-300/5 p-8"><CheckCircle2 size={32} className="text-emerald-300"/><h3 className="mt-4 text-3xl">Your project inquiry is saved.</h3><p className="mt-4 text-[#C9B99A]">Thank you. Ronald can now review your project and contact you at the email you provided. You have not been added to the newsletter.</p></div> : <form onSubmit={submit} className="space-y-5 rounded-2xl border border-white/15 bg-[#182635] p-5 sm:p-8">
        <div className="grid gap-5 sm:grid-cols-2"><label className="text-sm">Your name *<input required autoComplete="name" minLength={2} maxLength={255} value={form.name} onChange={e => setForm({...form,name:e.target.value})} className={inputClass}/></label><label className="text-sm">Email address *<input required type="email" autoComplete="email" maxLength={320} value={form.email} onChange={e => setForm({...form,email:e.target.value})} className={inputClass}/></label></div>
        <div className="grid gap-5 sm:grid-cols-2"><label className="text-sm">Business / author name *<input required minLength={2} maxLength={200} value={form.business} onChange={e => setForm({...form,business:e.target.value})} className={inputClass}/></label><label className="text-sm">Phone (optional)<input type="tel" autoComplete="tel" maxLength={50} value={form.phone} onChange={e => setForm({...form,phone:e.target.value})} className={inputClass}/></label></div>
        <label className="block text-sm">Interested in *<select value={form.package} onChange={e => setForm({...form,package:e.target.value as StudioInquiry['package']})} className={inputClass}>{['Brand Essentials','Author Launch','Business Identity','Writing & Copy','Monthly Care','Custom Project'].map(v => <option key={v}>{v}</option>)}</select></label>
        <div className="grid gap-5 sm:grid-cols-2"><label className="text-sm">Budget *<select value={form.budget} onChange={e => setForm({...form,budget:e.target.value as StudioInquiry['budget']})} className={inputClass}>{['Under $500','$500–$1,499','$1,500–$2,999','$3,000+','Need guidance'].map(v => <option key={v}>{v}</option>)}</select></label><label className="text-sm">Timeline *<select value={form.timeline} onChange={e => setForm({...form,timeline:e.target.value as StudioInquiry['timeline']})} className={inputClass}>{['Within a month','1–3 months','Exploring options'].map(v => <option key={v}>{v}</option>)}</select></label></div>
        <label className="block text-sm">Existing website (optional)<input type="url" placeholder="https://" maxLength={500} value={form.website} onChange={e => setForm({...form,website:e.target.value})} className={inputClass}/></label>
        <label className="block text-sm">What do you want to build? *<textarea required minLength={20} maxLength={1500} rows={5} value={form.message} onChange={e => setForm({...form,message:e.target.value})} className={inputClass} placeholder="Who is it for, and what should visitors be able to do?"/></label>
        <div aria-hidden="true" className="hidden"><label>Leave this empty<input tabIndex={-1} autoComplete="off" value={form.companyWebsite} onChange={e => setForm({...form,companyWebsite:e.target.value})}/></label></div>
        <label className="flex items-start gap-3 text-sm leading-relaxed text-[#C9B99A]"><input required type="checkbox" checked={form.consent} onChange={e => setForm({...form,consent:e.target.checked})} className="mt-1"/> <span>I agree that AASOTU Media Group LLC may store this inquiry and contact me about my project. <Link to="/privacy-policy" className="text-[#FFB840] underline">Privacy policy</Link>. This is not a newsletter signup.</span></label>
        {inquiry.error && <p role="alert" className="text-sm text-red-300">Your inquiry was not confirmed. {inquiry.error.message} You can also email Ronald directly.</p>}
        <button disabled={inquiry.isPending} className={`${linkClass} w-full disabled:opacity-50`}>{inquiry.isPending ? 'Saving your inquiry…' : 'Send project inquiry'} <ArrowRight size={17}/></button>
      </form>}
    </section>
  </main>;
}
