import { useEffect, useRef, useState } from 'react';
import { Link, useSearchParams } from 'react-router';
import { NOLAN_ARTICLE_PATH, NOLAN_RECORDS_DESCRIPTION, NOLAN_RECORDS_TITLE } from '../../contracts/nolan-records';
import manifest from '../data/nolan-captures.json';

const button = 'rounded-lg border border-white/30 px-3 py-2 text-sm hover:bg-white/10 disabled:opacity-40 focus-visible:outline focus-visible:outline-2 focus-visible:outline-[#FFB840]';
export default function NolanRecordsPage() {
  const [params, setParams] = useSearchParams();
  const number = Number(params.get('capture') || 2);
  const current = Math.max(1, Math.min(manifest.pages.length, Number.isInteger(number) ? number : 2));
  const page = manifest.pages[current - 1];
  const [zoom, setZoom] = useState(1);
  const [failed, setFailed] = useState(false);
  const dialog = useRef<HTMLDialogElement>(null);
  const go = (value: number) => { if (value < 1 || value > manifest.pages.length) return; setParams({ capture: String(value) }); setZoom(1); setFailed(false); };
  useEffect(() => { document.title = NOLAN_RECORDS_TITLE + ' | The King’s Take'; }, []);
  const image = <img key={current} src={page.image} onError={() => setFailed(true)} alt={`Capture ${current}: ${page.caption}. Existing source redactions and additional privacy redactions preserved.`} className="mx-auto block max-w-none" style={{ width: `${zoom * 100}%` }} />;
  const firstThumb = Math.floor((current - 1) / 12) * 12;
  const controls = <div className="flex flex-wrap items-center gap-2"><button className={button} disabled={current === 1} onClick={() => go(current - 1)}>← Previous</button><label className="flex items-center gap-2 text-sm">Capture <input aria-label="Capture number" type="number" min={1} max={manifest.pages.length} value={current} onChange={e => { if (e.target.value) go(Number(e.target.value)); }} className="w-20 rounded border border-white/30 bg-[#101b28] p-2"/> of {manifest.pages.length}</label><button className={button} disabled={current === manifest.pages.length} onClick={() => go(current + 1)}>Next →</button><button className={button} disabled={zoom <= 1} onClick={() => setZoom(v => Math.max(1, v - .25))} aria-label="Zoom out">−</button><span className="text-sm">{Math.round(zoom * 100)}%</span><button className={button} disabled={zoom >= 3} onClick={() => setZoom(v => Math.min(3, v + .25))} aria-label="Zoom in">+</button><button className={button} onClick={() => setZoom(1)}>Fit width</button></div>;
  return <main className="min-h-screen bg-[#101b28] px-4 pb-20 pt-28 text-[#F0EBE1] sm:px-8"><div className="mx-auto max-w-6xl">
    <Link to="/investigations" className="text-[#FFB840] underline">← Investigation collection</Link>
    <p className="mt-6 text-xs uppercase tracking-widest text-[#FFB840]">#TheKingsTake · AASOTU Media Group LLC</p><h1 className="mt-4 max-w-4xl text-4xl leading-tight sm:text-5xl">{NOLAN_RECORDS_TITLE}</h1><p className="mt-5 max-w-3xl text-lg leading-relaxed text-[#C9B99A]">{NOLAN_RECORDS_DESCRIPTION}</p>
    <p className="mt-5 text-sm text-[#C9B99A]">Viewer published October 6, 2026 · Source collection publication date not independently established</p>
    <section aria-labelledby="source-heading" className="my-8 rounded-xl border border-[#FFB840]/30 bg-[#182635] p-5"><h2 id="source-heading" className="text-2xl">Captured report pages: what you are viewing</h2><p className="mt-3 leading-relaxed text-[#C9B99A]">The supplied framebook contains 292 PDF pages: a cover, 272 report views labelled with printed pages 1–261, and 19 GPS presentation views. It reconstructs what appeared in four livestreams. Multiple captures can represent one printed page; printed page 151 is only partly visible. Numbered coverage does not establish that every page is complete or readable.</p><p className="mt-3 leading-relaxed text-[#C9B99A]">This is not a certified native Garrett Discovery PDF, authenticated database export, or complete phone extraction. Source redactions remain. This publication additionally withholds private account identifiers and unrelated personal material; Additional masks are identified in the caption. Message content is limited to legible July 4–5 activity dates; later or uncertain-date content is withheld. The 19 GPS views remain in the private source collection. Nothing hidden or unreadable has been reconstructed.</p><p className="mt-3 leading-relaxed text-[#C9B99A]">The device’s recorded movement, a vessel’s GPS movement, witness statements, and interpretations are different kinds of evidence. Snapchat activity and face-recognition settings alone do not identify who physically used the phone or establish Nolan’s location. A location animation is a presentation of selected points, not an uninterrupted location record.</p><div className="mt-4 flex flex-wrap gap-4 text-[#FFB840]"><Link to={NOLAN_ARTICLE_PATH} className="underline">Compare with our reporting</Link><a href="#record-timeline" className="underline">Dated message sequence ↓</a></div><p className="mt-4 text-sm text-[#C9B99A]">TheKing’sTake hosts this public-information evidence collection for direct review on our site. A downloadable edition is not offered here while redistribution terms remain unverified. The unaltered supplied framebook is retained privately for provenance and editorial review.</p></section>
    <section aria-label="Captured report page viewer" className="rounded-xl border border-white/20 bg-[#182635] p-3 sm:p-5">
      {controls}<div className="mt-4 flex flex-wrap items-center gap-4"><label className="text-sm">Jump to printed report page <select value={page.printed || ''} onChange={e => { const found = manifest.pages.find(p => p.printed === Number(e.target.value)); if (found) go(found.capture); }} className="ml-2 rounded border border-white/30 bg-[#101b28] p-2"><option value="">Cover / GPS views</option>{Array.from({length:261},(_,i)=><option key={i+1} value={i+1}>{i+1}{i===150?' · partial':''}</option>)}</select></label><button className={button} onClick={() => dialog.current?.showModal()}>Full-screen view</button></div>
      <p role="status" className="mt-4 text-sm text-[#FFB840]">Capture {current} · {page.caption}</p><figure className="mt-3"><div tabIndex={0} aria-label="Scrollable page image; use zoom controls to enlarge" className="max-h-[75vh] overflow-auto rounded border border-white/20 bg-white">{failed ? <p role="alert" className="p-6 text-black">This capture could not load. Please reload the page or choose another capture.</p> : image}</div><figcaption className="mt-3 text-sm leading-relaxed text-[#C9B99A]">{page.caption} · {page.note}</figcaption></figure>
      <nav aria-label="Page thumbnails" className="mt-5 grid grid-cols-3 gap-2 sm:grid-cols-6">{manifest.pages.slice(firstThumb,firstThumb+12).map(p=><button key={p.capture} aria-current={p.capture===current?'page':undefined} onClick={() => go(p.capture)} className={`rounded border p-2 text-left text-xs ${p.capture===current?'border-[#FFB840] bg-[#FFB840]/10':'border-white/20'}`}><img src={p.image} alt="" loading="lazy" className="h-24 w-full bg-white object-contain"/><span className="mt-2 block">Capture {p.capture}<br/>{p.printed ? `Printed p. ${p.printed}` : p.capture===1?'Collection cover':'GPS view'}</span></button>)}</nav>
    </section>
    <section id="record-timeline" className="scroll-mt-24 mt-12"><h2 className="text-3xl">Dated message sequence and readable excerpts</h2><p className="mt-3 max-w-3xl leading-relaxed text-[#C9B99A]">Only manually checked, readable excerpts are transcribed below. This is a selected transcript, not all messages. Times are reproduced as displayed; the report’s clock and activity-order limitations still apply. Message statements are participant accounts, not independently established events.</p><ol className="mt-6 space-y-4">{manifest.timeline.map(entry=><li key={entry.time+entry.capture} className="rounded-xl border border-white/15 p-5"><p className="text-sm text-[#FFB840]">{entry.time}</p><p className="mt-2 leading-relaxed">“{entry.text}”</p><p className="mt-2 text-sm text-[#C9B99A]">{entry.note}</p><button onClick={() => {go(entry.capture); document.querySelector('[aria-label="Captured report page viewer"]')?.scrollIntoView({behavior:'smooth',block:'start'});}} className="mt-3 text-[#FFB840] underline">Inspect capture {entry.capture} · printed page {manifest.pages[entry.capture-1].printed}</button></li>)}</ol></section>
    <dialog ref={dialog} aria-label="Full-screen captured report viewer" className="fixed inset-0 m-0 h-dvh max-h-none w-screen max-w-none bg-[#101b28] p-4 text-[#F0EBE1] backdrop:bg-black/80"><div className="flex flex-wrap justify-between gap-3">{controls}<button className={button} onClick={() => dialog.current?.close()}>Close full-screen</button></div><p className="my-3 text-sm">Capture {current} · {page.caption}</p><div className="h-[calc(100dvh-160px)] overflow-auto bg-white">{image}</div></dialog>
  </div></main>;
}
