import { Link } from 'react-router';
import { ArrowUpRight, Globe, PenTool } from 'lucide-react';
import ServiceChoices from '../components/ServiceChoices';
export default function ServicesPage() {
  return <main className="min-h-screen bg-[#101b28] text-[#F0EBE1]">
    <section className="relative overflow-hidden px-6 pb-16 pt-32 md:px-12"><div className="absolute inset-0 bg-cover bg-center" style={{backgroundImage:'linear-gradient(90deg,rgba(16,27,40,.97),rgba(16,27,40,.72)),url(/images/bg-services.jpg)'}}/><div className="relative mx-auto max-w-6xl"><p className="flex items-center gap-2 text-xs uppercase tracking-[.2em] text-[#FFB840]"><PenTool size={17}/> AASOTU · Creative services</p><h1 className="mt-6 max-w-3xl text-5xl leading-tight sm:text-6xl">Different goals.<br/><span className="text-[#FFB840]">The right kind of help.</span></h1><p className="mt-6 max-w-2xl text-lg leading-relaxed text-[#C9B99A]">A speech, a manuscript, a life story and a business offer each need a different approach. Choose by the result you need—not just the name of the service.</p><a href="#service-choices" className="mt-7 inline-block rounded-full bg-[#FFB840] px-6 py-3 font-semibold text-[#101b28]">Compare creative services</a></div></section>
    <section id="service-choices" className="mx-auto max-w-6xl scroll-mt-24 px-6 py-16"><ServiceChoices/><p className="mt-6 text-sm text-[#C9B99A]">Starting prices are for defined scopes. Deliverables, research, revision rounds and timing are agreed before work begins.</p></section>
    <section className="border-t border-white/10 bg-[#F0EBE1] px-6 py-12 text-[#182635]"><div className="mx-auto flex max-w-6xl flex-col gap-5 sm:flex-row sm:items-center sm:justify-between"><div><Globe size={25} className="mb-3 text-[#866021]"/><h2 className="text-3xl">Need the website and visual identity?</h2><p className="mt-2 max-w-xl text-sm leading-relaxed">Brand Studio has its own packages for identity design, author websites and business websites. Explore the work, compare packages and request a quote there.</p></div><Link to="/brand-studio" className="inline-flex shrink-0 items-center gap-2 self-start rounded-full bg-[#182635] px-6 py-3 text-[#F0EBE1]">Visit Brand Studio <ArrowUpRight size={17}/></Link></div></section>
  </main>;
}
