import { useState } from "react";
import { Link } from "react-router";
import { trpc } from "@/providers/trpc";
import { parseVideo } from "@contracts/video-news";
import NewsMemberCTA from "@/components/NewsMemberCTA";
export default function VideoNewsPage() {
 const query = trpc.blog.videoList.useQuery(); const [filter, setFilter] = useState("Latest");
 const filters = ["Latest", "Breaking", "Crime & Justice", "Investigations", "Community & Culture", "Featured"];
 const rows = (query.data || []).filter(p => parseVideo(p.videoNews)).filter(p => filter === "Latest" || (filter === "Breaking" ? p.content.includes("**BREAKING / DEVELOPING**") : filter === "Featured" ? p.featured : filter === "Crime & Justice" ? p.newsBeat === "crime-justice" : filter === "Investigations" ? p.category === "INVESTIGATIONS" : /community|culture/i.test(p.category)));
 return <main className="min-h-screen bg-[#14202E] px-6 pb-16 pt-28 text-[#F0EBE1]"><div className="mx-auto max-w-6xl"><Link to="/news-hub" className="text-[#FFB840]">← News Hub</Link><p className="mt-5 text-xs uppercase tracking-widest text-[#FFB840]">AASOTU Media Group LLC · #TheKingsTake</p><h1 className="my-4 text-4xl md:text-6xl">Video News</h1><p className="text-[#C9B99A]">Watch the brief. Read the evidence. Follow the developing story.</p><div className="my-6 flex flex-wrap gap-2" aria-label="Filter video reports">{filters.map(f => <button key={f} aria-pressed={f === filter} onClick={() => setFilter(f)} className={`rounded-full border px-4 py-2 text-sm ${f === filter ? "border-[#FFB840] text-[#FFB840]" : "border-white/20"}`}>{f}</button>)}</div>{query.isLoading && <p>Loading reports…</p>}{query.error && <p role="alert">Video reports are temporarily unavailable. Please try again.</p>}{!query.isLoading && !query.error && !rows.length && <p className="rounded-xl border border-white/10 p-6">No published video reports in this section yet. <Link to="/news-hub" className="text-[#FFB840]">Read the latest news →</Link></p>}<div className="grid gap-6 sm:grid-cols-2 lg:grid-cols-3">{rows.map(p => {const v = parseVideo(p.videoNews)!; return <Link key={p.id} to={`/blog/${p.slug}`} className="overflow-hidden rounded-2xl border border-white/10 bg-[#182635]">{v.poster && <img src={v.poster} alt="" loading="lazy" className="aspect-video w-full object-cover" />}<div className="p-5"><p className="text-xs text-[#FFB840]">WATCH · {v.aspectRatio}</p><h2 className="mt-2 text-2xl">{p.title}</h2><p className="mt-3 text-sm text-[#C9B99A]">{p.excerpt}</p><span className="mt-4 block text-[#FFB840]">Watch & read full report →</span></div></Link>})}</div><NewsMemberCTA /></div></main>;
}
