import { useState, type FormEvent } from 'react';
import { CreditCard, X } from 'lucide-react';
import { trpc } from '@/providers/trpc';
import { studioPaymentOffers } from '../../contracts/studio-payments';
const field = 'mt-2 w-full rounded-lg border border-white/15 bg-[#101b28] p-3 text-base text-[#F0EBE1]';
export function StudioCheckout({ packageName }: { packageName: string }) {
  const offer = studioPaymentOffers.find(item => item.package === packageName)!;
  const [open, setOpen] = useState(false);
  const [form, setForm] = useState({ name: '', email: '', business: '', project: '', acknowledgeScope: false, companyWebsite: '' });
  const configuration = trpc.studioPayments.configuration.useQuery(undefined, { staleTime: 60_000 });
  const checkout = trpc.studioPayments.checkout.useMutation({ onSuccess: result => { window.location.assign(result.url); } });
  const submit = (event: FormEvent) => { event.preventDefault(); if (form.acknowledgeScope) checkout.mutate({ ...form, acknowledgeScope: true, offerId: offer.id }); };
  return <div className="mt-3">
    <button disabled={!configuration.data?.ready} onClick={() => setOpen(true)} className="flex w-full items-center justify-center gap-2 rounded-full border border-[#FFB840]/70 px-4 py-3 text-sm text-[#FFB840] disabled:cursor-not-allowed disabled:opacity-50"><CreditCard size={16}/>{configuration.isLoading ? 'Checking payment availability…' : offer.label}</button>
    {!configuration.isLoading && !configuration.data?.ready && <p className="mt-2 text-center text-xs leading-relaxed text-[#C9B99A]">Online checkout is being connected. Use “Discuss this package” to get started.</p>}
    {open && <div role="dialog" aria-modal="true" aria-labelledby={`checkout-${offer.id}`} className="fixed inset-0 z-[100] overflow-y-auto bg-black/80 px-4 py-10" onKeyDown={e => { if (e.key === 'Escape' && !checkout.isPending) setOpen(false); }}><div className="mx-auto max-w-xl rounded-2xl border border-[#FFB840]/30 bg-[#182635] p-6 shadow-2xl sm:p-8"><div className="flex items-start justify-between gap-3"><h2 id={`checkout-${offer.id}`} className="text-2xl">{offer.package}</h2><button disabled={checkout.isPending} aria-label="Close checkout" onClick={() => setOpen(false)}><X/></button></div>
    <p className="mt-4 text-3xl text-[#FFB840]">${(offer.amount / 100).toLocaleString('en-US', { minimumFractionDigits: 2 })} <span className="text-sm">{offer.kind === 'deposit' ? 'deposit today' : 'package payment'}</span></p>
    <p className="mt-3 text-sm leading-relaxed text-[#C9B99A]">{offer.kind === 'deposit' ? 'This is 50% of the $2,495 base package. The remaining $1,247.50 is due in two stages: $748.50 at design approval and $499 before launch. Additional work and provider costs require a separate agreement.' : 'This covers the listed Brand Essentials scope and two consolidated revision rounds. Website development and provider costs are separate.'} Ronald will contact you about your project and schedule. Payment does not promise an immediate launch or a specific business outcome.</p>
    <form onSubmit={submit} className="mt-6 space-y-4"><label className="block text-sm">Your name *<input required autoComplete="name" minLength={2} maxLength={255} autoFocus value={form.name} onChange={e => setForm({...form,name:e.target.value})} className={field}/></label><label className="block text-sm">Email for your project *<input required type="email" autoComplete="email" maxLength={320} value={form.email} onChange={e => setForm({...form,email:e.target.value})} className={field}/></label><label className="block text-sm">Business / author name *<input required minLength={2} maxLength={200} value={form.business} onChange={e => setForm({...form,business:e.target.value})} className={field}/></label><label className="block text-sm">Tell Ronald about your project *<textarea required minLength={20} maxLength={1500} rows={3} value={form.project} onChange={e => setForm({...form,project:e.target.value})} className={field}/></label><div className="hidden" aria-hidden="true"><input tabIndex={-1} autoComplete="off" value={form.companyWebsite} onChange={e => setForm({...form,companyWebsite:e.target.value})}/></div><label className="flex items-start gap-3 text-sm leading-relaxed text-[#C9B99A]"><input required type="checkbox" checked={form.acknowledgeScope} onChange={e=>setForm({...form,acknowledgeScope:e.target.checked})} className="mt-1"/><span>I understand the listed scope and payment schedule and agree to be contacted about this project. This purchase does not subscribe me to marketing emails. <a href="/privacy-policy" target="_blank" rel="noreferrer" className="underline">Privacy policy</a>.</span></label>{checkout.error && <p role="alert" className="text-sm text-red-300">{checkout.error.message}</p>}<button disabled={checkout.isPending} className="w-full rounded-full bg-[#FFB840] px-6 py-3 font-semibold text-[#101b28] disabled:opacity-50">{checkout.isPending ? 'Opening secure checkout…' : 'Continue to Stripe'}</button><p className="text-center text-xs text-[#C9B99A]">Your card details are entered securely on Stripe.</p></form></div></div>}
  </div>;
}
export function StudioPaymentResult() {
  const params = new URLSearchParams(window.location.search);
  const sessionId = params.get('session_id') || '';
  const success = params.get('checkout') === 'success';
  const valid = /^cs_(live|test)_[A-Za-z0-9]+$/.test(sessionId);
  const query = trpc.studioPayments.status.useQuery({ sessionId }, { enabled: success && valid, refetchInterval: result => result.state.data?.status === 'pending' ? 3000 : false, retry: 1 });
  if (params.get('checkout') === 'cancelled') return <div role="status" className="border-b border-white/15 bg-[#182635] px-6 py-6 pt-24 text-center">Checkout was cancelled. No completed payment is recorded by this return. You can try again or discuss the package.</div>;
  if (!success) return null;
  const paid = query.data?.status === 'paid';
  return <div role="status" className="border-b border-[#FFB840]/30 bg-[#182635] px-6 pb-6 pt-24 text-center"><h2 className="text-2xl text-[#FFB840]">{paid ? 'Your payment is confirmed.' : 'Checking your payment confirmation.'}</h2><p className="mx-auto mt-3 max-w-2xl text-sm text-[#C9B99A]">{paid ? `${query.data?.package} · $${((query.data?.amount || 0)/100).toFixed(2)} received. Ronald can now see your order and contact you about next steps.` : 'A return from checkout alone does not confirm payment. If confirmation takes longer, check your Stripe receipt or email aasotumediagroup@gmail.com. Please do not pay a second time.'}</p>{query.error && <p className="mt-2 text-sm text-amber-300">{query.error.message}</p>}</div>;
}
