import { ArrowRight, CalendarDays, LayoutDashboard, Users, Workflow } from 'lucide-react';

export function StudioScopeGuide({ onCustomProject }: { onCustomProject: () => void }) {
  return <section id="studio-scope" className="scroll-mt-24 border-t border-white/10 px-6 pb-16 pt-12 md:px-12"><div className="mx-auto max-w-6xl">
    <p className="text-xs uppercase tracking-[0.18em] text-[#FFB840]">Understand your investment</p>
    <h2 className="mt-4 text-4xl sm:text-5xl">A website that fits the way you work.</h2>
    <p className="mt-5 max-w-3xl leading-relaxed text-[#C9B99A]">Start with what your customers need to do. A clear online presence may be the right fit today. When your business needs its own workflows, a custom project can connect the public website to the tools you use behind the scenes.</p>
    <div className="mt-8 grid gap-5 lg:grid-cols-2">
      <article className="rounded-2xl border border-white/15 bg-[#182635] p-6 sm:p-8"><p className="text-xs uppercase tracking-widest text-[#A9C7FF]">Defined website packages</p><h3 className="mt-3 text-2xl">Introduce your work. Give visitors a next step.</h3><p className="mt-4 leading-relaxed text-[#C9B99A]">Author Launch and Business Identity start at $2,495 for up to five responsive pages, brand direction, introductory copy, and the features listed in your package. Business Identity includes one booking or payment-provider integration.</p><p className="mt-4 text-sm leading-relaxed text-[#C9B99A]">A good fit when customers need to understand your services, readers need to discover your book, or visitors need to make an inquiry or use an agreed provider’s booking or payment flow. Brand Essentials is a separate $495 visual identity package.</p></article>
      <article className="rounded-2xl border border-[#FFB840]/35 bg-[#2b281e] p-6 sm:p-8"><p className="text-xs uppercase tracking-widest text-[#FFB840]">Custom websites & applications</p><h3 className="mt-3 text-2xl">Build around your business’s own process.</h3><p className="mt-4 leading-relaxed text-[#C9B99A]">A custom project may include an owner dashboard, customer accounts, tailored scheduling, connected services, or automation. These features are scoped and quoted separately after we understand your requirements.</p><p className="mt-4 text-sm leading-relaxed text-[#C9B99A]">The premium investment covers the additional planning, design, development, testing, and handoff needed for your agreed workflows. Choose this level when those capabilities solve a practical need for your customers or team.</p></article>
    </div>
    <h3 className="mt-12 text-2xl sm:text-3xl">What custom features can help you do</h3><p className="mt-3 text-sm leading-relaxed text-[#C9B99A]">Examples to discuss for your project; these are not automatically included in a website package.</p>
    <div className="mt-6 grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{[
      { icon: CalendarDays, title: 'Tailored booking', text: 'Let customers book around your services and availability, with rules designed for how your business schedules work.' },
      { icon: LayoutDashboard, title: 'Owner dashboard', text: 'Bring agreed tasks such as managing appointments, content, or orders into a dedicated workspace.' },
      { icon: Users, title: 'Customer accounts', text: 'Give customers a place to return to their agreed bookings, purchases, or member content, with appropriate access controls.' },
      { icon: Workflow, title: 'Automation & agents', text: 'Reduce repeated steps such as reminders or routing inquiries, with agreed permissions, review controls, and clear limits.' },
    ].map(({ icon: Icon, title, text }) => <article key={title} className="rounded-xl border border-white/10 bg-[#182635]/70 p-5"><Icon size={24} className="text-[#FFB840]" /><h4 className="mt-4 text-lg">{title}</h4><p className="mt-3 text-sm leading-relaxed text-[#C9B99A]">{text}</p></article>)}</div>
    <div className="mt-8 rounded-2xl border border-white/15 p-6 sm:p-8"><h3 className="text-2xl">Know what you are approving.</h3><p className="mt-4 max-w-3xl leading-relaxed text-[#C9B99A]">Your written scope sets out the pages and features, what you need to supply, revision rounds, schedule, payment milestones, and how we will check the agreed work before launch. We also agree on account ownership, handoff, and any support after launch.</p><p className="mt-4 max-w-3xl text-sm leading-relaxed text-[#C9B99A]">Hosting, paid providers, and automation services can carry ongoing costs. We identify those costs during scoping. Custom feature maintenance and support are quoted separately; the $79 Monthly Care plan covers routine checks and up to 30 minutes of small content updates.</p><button onClick={onCustomProject} className="mt-6 inline-flex items-center justify-center gap-2 rounded-full bg-[#FFB840] px-6 py-3 font-semibold text-[#101b28] transition hover:bg-[#ffd485]">Discuss a custom project <ArrowRight size={18} /></button></div>
  </div></section>;
}
