export const NEWS_BEATS = [
  { id: "crime-justice", label: "Crime & Justice", detail: "Criminal cases, courts, policing, public safety and accountability.", focus: "Crime and justice developments: major criminal cases, court filings, policing, public safety, civil liberties and accountability. Prioritize court records, prosecutors, defense filings, police records and established local reporting. Preserve the presumption of innocence, distinguish allegations from findings, and never imply an arrest is a conviction." },
  { id: "ai-policy", label: "AI & Tech Policy", detail: "AI breakthroughs, products, power, regulation and the everyday costs of automation.", focus: "AI models, artificial intelligence, creator tools, public accountability, labor, scams and cybersecurity. Attribute executive claims, distinguish model capabilities from hype, and explain who benefits and who bears the risks." },
  { id: "weather", label: "Breaking Weather", detail: "Major storms, flooding, emergencies and official alerts.", focus: "Major weather threats, storms, flooding, heat and emergency alerts. Prioritize NOAA, NWS, WMO and local agencies. Do not present stale forecasts as current alerts." },
  { id: "us-conflicts", label: "U.S. Conflicts", detail: "Military action, diplomacy, war powers and consequences for Americans.", focus: "U.S. military conflicts, Iran, war powers, diplomacy and civilian consequences. Distinguish official claims from independently confirmed facts." },
  { id: "gaza-israel", label: "Gaza & Israel", detail: "Civilian impact, humanitarian access, diplomacy and regional developments.", focus: "Gaza and Israel: civilian impact, humanitarian access, hostages, diplomacy and military developments. Attribute casualty figures and contested claims." },
  { id: "ukraine", label: "Ukraine", detail: "The war, humanitarian conditions, diplomacy and U.S. policy.", focus: "Ukraine: war, humanitarian conditions, diplomacy, reconstruction and U.S. policy. Attribute battlefield claims and independently verify where possible." },
  { id: "sahel", label: "Burkina Faso & the Sahel", detail: "Ibrahim Traoré, regional alliances, governance and economic sovereignty.", focus: "Burkina Faso, Ibrahim Traoré and the Sahel: policies, regional alliances, governance, resource sovereignty and security. Do not assume promotional viral claims are true; include evidence and limitations." },
  { id: "africa", label: "Africa & Decolonization", detail: "Sovereignty, resource control, colonial legacies and community movements.", focus: "African sovereignty, decolonization, resource control, colonial legacies, regional institutions and community movements. Cover a different country or story from the Sahel beat. Do not imply every African movement has the same motives." },
  { id: "environment", label: "Earth, Energy & Science", detail: "Alternative energy, restoration and new science that can improve life on Earth.", focus: "Environment, alternative and renewable energy, storage, ecosystem restoration, water and scientific advances improving Earth. Prioritize original research and institutions. Explain evidence, scale, limitations and lab versus commercial deployment." },
] as const;
export type NewsBeatId = typeof NEWS_BEATS[number]["id"];
export function newsBeat(id: string | null | undefined) { return NEWS_BEATS.find(beat => beat.id === id); }
